apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: auth-backend
  template:
    metadata:
      labels:
        app: auth-backend
    spec:
      containers:
        - name: auth-backend
          image: auth-backend:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 8080
          env:
            - name: WEB_SERVER_PORT # variables ambient
              value: "8080"
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
          resources:
            requests:
              memory: "64Mi"
              cpu: "256m"
            limits:
              memory: "128Mi"
              cpu: "512m"
