apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: auth-backend
  template:
    metadata:
      labels:
        app: auth-backend
    spec:
      initContainers:
        - name: wait-for-postgres
          image: busybox
          command:
            [
              "sh",
              "-c",
              "until nc -z postgres 5432; do echo waiting for postgres; sleep 3; done;",
            ]

        - name: wait-for-rabbitmq
          image: busybox
          command:
            [
              "sh",
              "-c",
              "until nc -z rabbitmq 5672; do echo waiting for rabbitmq; sleep 3; done;",
            ]

      containers:
        - name: auth-backend
          image: higordeveloper/authbackend:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          env:
            - name: WEB_SERVER_PORT # variables ambient
              value: "8080"
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
          resources:
            requests:
              memory: "64Mi"
              cpu: "256m"
            limits:
              memory: "128Mi"
              cpu: "512m"
